apiVersion: apps/v1
kind: Deployment
metadata:
  name: tobias
spec:
  replicas: 3
  selector:
    matchLabels:
      run: tobias
  template:
    metadata:
      labels:
        run: tobias
    spec:
      containers:
      - image: predic8/mynginx:6
        name: tobias3
        readinessProbe:
          httpGet:
            path: /
            port: 80
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - "sleep 1"
        resources:
          requests:
            memory: 1Gi
            cpu: 512m
          limits:
            memory: 1Gi
            cpu: 1024m
          # wenn Pod <1Gi nutzt, wird in Ruhe gelassen
          # wenn Pod 1..2Gi nutzt, wird er evtl ersetzt durch einen neuen Pod auf einem anderen Node, der mehr RAM frei hat
          # wenn Pod >2Gi nutzt, ist er tot (->Neustart).
      dnsPolicy: ClusterFirst
      restartPolicy: Always
